[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "app"
version = "0.2"
requires-python = ">=3.8"
dependencies = [
  "flask~=2.2",
]

[project.scripts]
app = "app.runserver:main"

[tool.setuptools]
packages = ["app"]
